apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: maturidade-digital
  labels:
    app: maturidade-digital-backend
spec:
  selector:
    app: maturidade-digital-backend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
