apiVersion: v1
kind: ConfigMap
metadata:
  name: maturidade-digital-config
  namespace: maturidade-digital
data:
  NODE_ENV: "production"
  PORT: "8080"
  FRONTEND_URL: "https://maturidade.sebraemg.com.br"
  CORS_ORIGIN: "https://sebraemg.com.br,https://www.sebraemg.com.br,https://maturidade.sebraemg.com.br"
  DIRECTUS_URL: "http://directus-service:8055"
  KEYCLOAK_REALM: "externo"
  KEYCLOAK_AUTH_SERVER_URL: "https://auth.sebrae-mg.com.br"
  KEYCLOAK_SSL_REQUIRED: "external"
  KEYCLOAK_RESOURCE: "maturidadedigital-backend"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "maturidade_digital"
  DB_USER: "maturidade"
  REDIS_URL: "redis://redis-service:6379"
