apiVersion: v1
kind: Secret
metadata:
  name: maturidade-digital-secrets
  namespace: maturidade-digital
type: Opaque
data:
  # Base64 encoded secrets
  DIRECTUS_TOKEN: <BASE64_ENCODED_TOKEN>
  DIRECTUS_EMAIL: <BASE64_ENCODED_EMAIL>
  DIRECTUS_PASSWORD: <BASE64_ENCODED_PASSWORD>
  DIRECTUS_SECRET: <BASE64_ENCODED_SECRET>
  KEYCLOAK_SECRET: <BASE64_ENCODED_KEYCLOAK_SECRET>
  DB_PASSWORD: <BASE64_ENCODED_DB_PASSWORD>
  MYSQL_ROOT_PASSWORD: <BASE64_ENCODED_MYSQL_ROOT_PASSWORD>
